name: My First Action
description: "My first docker action"

inputs:
  who-to-greet:
    required: true
    default: "world"
    description: "who to greet"
outputs:
  time:
    description: "When it was run"

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.who-to-greet }}
  
