name: GitHub Actions Demo

on:
  push:
    branches: main
    paths-ignore: ".github/**"
  pull_request:
    branches: main
  schedule:
    - cron: 15 6 * * SUN
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Event ${{ github.event_name }}"
      - run: echo "Branch ${{ github.ref }}"
      - run: tree
